# Generated by Django 4.0.5 on 2022-06-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=255, verbose_name='DocName')),
                ('document_file', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
