# Generated by Django 4.0.5 on 2022-06-28 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_job_user_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user_ref'),
        ),
    ]
